// SPDX-License-Identifier: AGPL-3.0-or-later

package app

const pageTemplates = `{{define "home"}}<!doctype html><html><head><title>Shauth</title><meta name="viewport" content="width=device-width,initial-scale=1"><script src="https://unpkg.com/htmx.org@2.0.8"></script><style>body{font:16px system-ui;max-width:56rem;margin:3rem auto;padding:0 1rem;color:#24292f}a{color:#0969da}nav{display:flex;gap:1rem;align-items:center}table{border-collapse:collapse;width:100%}td,th{padding:.6rem;border-bottom:1px solid #d0d7de;text-align:left}button{padding:.5rem .8rem}main{margin-top:2rem}</style></head><body><nav><strong>Shauth</strong><a href="/">Home</a>{{if .SignedIn}}<a href="/admin">Admin</a><a href="/monitoring">Monitoring</a><form method="post" action="/logout"><button>Sign out</button></form>{{else}}<a href="/login">Sign in</a>{{end}}</nav><main>{{if .SignedIn}}<h1>Signed in as {{.User.Username}}</h1><p>{{.User.Email}} · {{.User.Role}}</p>{{else}}<h1>e6qu identity service</h1><p>Sign in to continue.</p>{{end}}</main></body></html>{{end}}
{{define "admin"}}<!doctype html><html><head><title>Administration — Shauth</title></head><body><h1>Private administration</h1><nav><a href="/admin/users">Users and local accounts</a> · <a href="/admin/github">GitHub access mappings</a> · <a href="/admin/invitations">Email invitations</a> · <a href="/monitoring">Monitoring</a></nav></body></html>{{end}}
{{define "login"}}<!doctype html><html><head><title>Sign in — Shauth</title><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font:16px system-ui;max-width:32rem;margin:4rem auto;padding:0 1rem}input,button{box-sizing:border-box;width:100%;padding:.7rem;margin:.3rem 0}.error{color:#cf222e}</style></head><body><h1>Sign in</h1>{{if .Error}}<p class="error">{{.Error}}</p>{{end}}<p><a href="/oauth/github">Continue with GitHub</a></p><hr><form method="post" action="/login"><input type="hidden" name="next" value="{{.Next}}"><label>Username<input name="username" autocomplete="username" required></label><label>Password<input type="password" name="password" autocomplete="current-password" required></label><button>Sign in with password</button></form></body></html>{{end}}
{{define "consent"}}<!doctype html><html><head><title>Authorize application — Shauth</title></head><body><h1>Authorize application</h1><p>Requested access: {{range .Scopes}}<code>{{.}}</code> {{end}}</p><form method="post" action="/oauth/consent"><input type="hidden" name="challenge" value="{{.Challenge}}">{{range .Scopes}}<input type="hidden" name="scope" value="{{.}}">{{end}}<button>Authorize</button></form></body></html>{{end}}
{{define "users"}}<!doctype html><html><head><title>Users — Shauth</title><script src="https://unpkg.com/htmx.org@2.0.8"></script></head><body><nav><a href="/">Shauth</a> · <a href="/monitoring">Monitoring</a></nav><h1>Users</h1><form method="post" action="/admin/users" hx-post="/admin/users" hx-target="#users" hx-swap="afterbegin"><h2>Create local user</h2><input name="username" placeholder="Username" required><input name="email" type="email" placeholder="Email" required><input name="password" type="password" placeholder="Password (14+ characters)" required><select name="role"><option value="developer">Developer</option><option value="admin">Administrator</option></select><button>Create user</button></form><form method="get"><input name="q" value="{{.Query}}" placeholder="Search users"><button>Search</button></form><table><thead><tr><th>User</th><th>Role</th><th>GitHub</th><th>Created</th></tr></thead><tbody id="users">{{range .Users}}{{template "user-row" .}}{{end}}</tbody></table></body></html>{{end}}
{{define "user-row"}}<tr><td><a href="/admin/users/{{.ID}}/sessions">{{.Username}}</a><br>{{.Email}}</td><td>{{.Role}}</td><td>{{.GitHubLogin}}</td><td>{{.CreatedAt}}</td></tr>{{end}}
{{define "accept-invitation"}}<!doctype html><html><head><title>Accept invitation — Shauth</title></head><body><h1>Accept invitation</h1><form method="post" action="/accept-invitation"><input type="hidden" name="token" value="{{.Token}}"><input name="username" placeholder="Username" required><input name="password" type="password" placeholder="Password (14+ characters)" required><button>Create account</button></form></body></html>{{end}}
{{define "invitations"}}<!doctype html><html><head><title>Invite — Shauth</title></head><body><nav><a href="/admin/users">Users</a></nav><h1>Invite by email</h1><form method="post" action="/admin/invitations"><input name="email" type="email" placeholder="Email" required><select name="role"><option value="developer">Developer</option><option value="admin">Administrator</option></select><button>Send invitation</button></form></body></html>{{end}}
{{define "github-mappings"}}<!doctype html><html><head><title>GitHub access — Shauth</title></head><body><nav><a href="/admin">Administration</a></nav><h1>GitHub access mappings</h1><p>Admins override developers when more than one mapping matches.</p><form method="post" action="/admin/github"><label>Match<select name="kind"><option value="user">GitHub user</option><option value="organization">GitHub organization</option><option value="team">GitHub team</option></select></label><label>Target<input name="target" required placeholder="e6qu-org/e6qu-org-members for a team"></label><label>Role<select name="role"><option value="developer">Developer</option><option value="admin">Administrator</option></select></label><button>Add mapping</button></form><table><thead><tr><th>Match</th><th>Target</th><th>Role</th><th></th></tr></thead><tbody>{{range .Mappings}}<tr><td>{{.Kind}}</td><td>{{.Target}}</td><td>{{.Role}}</td><td><form method="post" action="/admin/github/{{.ID}}/delete"><button>Delete</button></form></td></tr>{{end}}</tbody></table></body></html>{{end}}
{{define "sessions"}}<!doctype html><html><head><title>Sessions — Shauth</title></head><body><nav><a href="/admin/users">Users</a></nav><h1>Sessions</h1><form method="post" action="/admin/users/{{.UserID}}/sessions/revoke"><button>Invalidate all active sessions</button></form><table><thead><tr><th>Created</th><th>Last seen</th><th>Device</th><th>State</th><th></th></tr></thead><tbody>{{range .Sessions}}<tr><td>{{.CreatedAt}}</td><td>{{.LastSeen}}</td><td>{{.UserAgent}}<br>{{.RemoteIP}}</td><td>{{if .RevokedAt}}revoked{{else}}active{{end}}</td><td>{{if not .RevokedAt}}<form method="post" action="/admin/sessions/{{.ID}}/revoke"><button>Invalidate</button></form>{{end}}</td></tr>{{end}}</tbody></table></body></html>{{end}}
{{define "monitoring"}}<!doctype html><html><head><title>Monitoring — Shauth</title></head><body><nav><a href="/admin/users">Users</a></nav><h1>Monitoring</h1><p>PostgreSQL session store: healthy.</p><p>Ory Hydra: {{if .HydraHealthy}}healthy{{else}}unavailable{{end}}.</p><p>Active browser sessions: {{.ActiveSessions}}</p><p>Observed at: {{.Now}}</p></body></html>{{end}}`
