# SPDX-License-Identifier: AGPL-3.0-or-later
# Local development only. Production sets the same values through the
# container environment in terraform/main.tf; compose.yaml sets the rest.
serve: {}
strategies:
  access_token: jwt

ttl:
  access_token: 15m
  refresh_token: 720h
  id_token: 15m
  auth_code: 10m
